import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";

import { _getQuestions, _saveQuestionAnswer, _saveQuestion } from "../../_DATA";

const initialState = {
  status: "idle",
  data: {},
};

export const fetchAllQuestionsAsync = createAsyncThunk(
  "questions/fetchAll",
  async () => {
    const questions = await _getQuestions();
    // The value we return becomes the `fulfilled` action payload
    return questions;
  }
);

export const saveQuestionAnswerAsync = createAsyncThunk(
  "questions/saveQuestionAnswer",
  async ({ authedUser, qid, answer }, { dispatch }) => {
    let input = { authedUser, qid, answer };
    const isSaveSucceeded = await _saveQuestionAnswer(input);
    if (isSaveSucceeded) {
      // reload questions into store from data-store
      dispatch(fetchAllQuestionsAsync());
    }
    // The value we return becomes the `fulfilled` action payload
    return isSaveSucceeded;
  }
);

export const saveQuestionAsync = createAsyncThunk(
  "questions/saveQuestion",
  async ({ author, optionOneText, optionTwoText }, { dispatch }) => {
    let questionData = { author, optionOneText, optionTwoText };
    const addedQuestion = await _saveQuestion(questionData);

    // reload questions into store from data-store
    dispatch(fetchAllQuestionsAsync());

    // The value we return becomes the `fulfilled` action payload
    return addedQuestion;
  }
);

export const questionsSlice = createSlice({
  name: "questions",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchAllQuestionsAsync.pending, (state, action) => {
        // Redux Toolkit uses Immer to generate new state from existing-state
        state.status = "pending";
      })
      .addCase(fetchAllQuestionsAsync.fulfilled, (state, action) => {
        // Redux Toolkit uses Immer to generate new state from existing-state
        state.data = Object.assign({}, state.data, { ...action.payload });
        state.status = "loaded";
      });
  },
});

export default questionsSlice.reducer;
